# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pokemons CI

defaults:
  run:
    shell: bash
    working-directory: packages/front

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  REACT_APP_API_BASE: 'http://localhost:1337/api'
  REACT_APP_POKEMON_API_BASE: 'https://pokeapi.co/api/v2'
  HOST: 0.0.0.0
  PORT: 1337
  APP_KEYS: HNC+61o5qtC1z1pPlAp9mA==,FukCKk/d2gclW0m/xx7xuQ==,ZgVfi2Zv87/hjRGYZ5ueKA==,oa1opOkVHqpZ474vhXdkJQ==

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn test --watch=false

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: yarn install --frozen-lockfile
          build: yarn dev
          start: yarn test-cypress --watch=false
